// <auto-generated />
namespace MovieTicketBooking.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class admintable20 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(admintable20));
        
        string IMigrationMetadata.Id
        {
            get { return "202109231524265_admin-table2.0"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
